version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://host.docker.internal:8000/api/v1
